# Generated by Django 4.2.4 on 2023-10-09 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0075_annotationguide_is_public"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="relatedfile",
            unique_together=set(),
        ),
    ]
